name: Daily Macro Update

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install
      run: pip install requests beautifulsoup4 lxml

    - name: Run
      run: python crawler.py

    - name: Commit
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html
        git commit -m "update" || exit 0
        git push
